# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1012a-hcen101.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1012a-hcen101-device.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen104.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen104-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen104-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen1002a.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen1002a-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen1002a-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen1002b.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen1002b-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-hcen1002b-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1046a-hcen1004.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1046a-hcen1004-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1046a-hcen1004-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1046a-hcen1004a.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1046a-hcen1004a-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1046a-hcen1004a-usdpaa.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
