# SPDX-License-Identifier: GPL-2.0

#dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-ag10025ga.dtb
#dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-ag10025ga-sdk.dtb
#dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-ag10025ga-usdpaa.dtb
#dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-ag10025gb.dtb
#dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-ag10025gb-sdk.dtb
#dtb-$(CONFIG_ARCH_LAYERSCAPE) += hc-ls1043a-ag10025gb-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002at/hc-ls1043a-ag1002at.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002at/hc-ls1043a-ag1002at-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002at/hc-ls1043a-ag1002at-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag104a/hc-ls1043a-ag104a.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag104a/hc-ls1043a-ag104a-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag104a/hc-ls1043a-ag104a-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag104am/hc-ls1043a-ag104am.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag104am/hc-ls1043a-ag104am-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag104am/hc-ls1043a-ag104am-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002at-device/hc-ls1043a-ag1002at-device.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002at-device/hc-ls1043a-ag1002at-sdk-device.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002ae/hc-ls1043a-ag1002ae.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002ae/hc-ls1043a-ag1002ae-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002ae/hc-ls1043a-ag1002ae-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += agedge100/hc-ls1043a-agedge100.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += agedge100/hc-ls1043a-agedge100-sdk.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += agedge100/hc-ls1043a-agedge100-usdpaa.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002ad/hc-ls1043a-ag1002ad.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002ad/hc-ls1043a-ag1002ad-sdk.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag1002am/hc-ls1043a-ag1002am-sdk.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag101a/hclink-ls1012a-ag101a.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag101asdm/hclink-ls1012a-ag101asdm.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag101asdp/hclink-ls1012a-ag101asdp.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += a5g121/hclink-ls1012a-a5g121.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += secam20/hc-ls1043a-secam20-sdk.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += tau001/hc-ls1043a-tau001-sdk.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += gt001a/hc-ls1046a-gt001a-sdk.dtb

dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag102ao/hc-ls1043a-ag102ao.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += ag102ao/hc-ls1043a-ag102ao-sdk.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
