obj-$(CONFIG_AG1002AE_FPGA)		+= ag1002ae_fpga/
obj-$(CONFIG_AG1002AD_IO)		+= ag1002ad_io/
obj-$(CONFIG_AG1002ADX_WDT)		+= ag1002adx_wdt/
obj-$(CONFIG_LDTEA100_FPGA)		+= ldtea100_fpga/
obj-$(CONFIG_AG1002AE_SC1161Y)		+= ag1002ae_sc1161y/
obj-$(CONFIG_IOT5060)		+= iot5060/
obj-$(CONFIG_AG102AO_IO)		+= ag102ao_io/

